# Generated by Django 5.2.11 on 2026-06-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='roadvideo',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20),
        ),
    ]
