# Generated by Django 5.2.11 on 2026-05-08 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'ordering': ['name'], 'verbose_name': 'Камера', 'verbose_name_plural': 'Камеры'},
        ),
        migrations.AddField(
            model_name='camera',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='camera',
            name='location_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес установки'),
        ),
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('inactive', 'Неактивна'), ('maintenance', 'Обслуживание'), ('error', 'Ошибка')], db_index=True, default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='camera',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='rtsp_url',
            field=models.URLField(help_text='Пример: rtsp://user:pass@192.168.1.1:554/stream', max_length=500, verbose_name='RTSP URL'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['status', 'name'], name='cameras_cam_status_c78ade_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['latitude', 'longitude'], name='cameras_cam_latitud_57d02b_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['is_active'], name='cameras_cam_is_acti_21ea5e_idx'),
        ),
    ]
