# Generated by Django 5.2.11 on 2026-04-27 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('streaming', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('STREAM', 'Stream')], max_length=10)),
                ('defect_type', models.CharField(choices=[('POTHOLE', 'Pothole'), ('CRACK', 'Crack'), ('ALLIGATOR_CRACK', 'Alligator Crack'), ('ROAD_MARKING', 'Road Marking'), ('OTHER', 'Other')], max_length=30)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('confidence', models.FloatField()),
                ('bbox', models.JSONField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('timestamp_in_video', models.FloatField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('road_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.roadimage')),
                ('road_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.roadvideo')),
                ('stream_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='streaming.streamsession')),
            ],
        ),
    ]
