# Generated by Django 5.2.11 on 2026-06-12 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Ключ кластера')),
                ('center_latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта центра')),
                ('center_longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота центра')),
                ('radius_meters', models.FloatField(default=8.0, verbose_name='Радиус (м)')),
                ('defect_count', models.PositiveIntegerField(default=1, verbose_name='Количество дефектов')),
                ('max_confidence', models.FloatField(verbose_name='Макс. уверенность')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_defect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='defects.defect', verbose_name='Главный дефект')),
            ],
            options={
                'verbose_name': 'Кластер дефектов',
                'verbose_name_plural': 'Кластеры дефектов',
                'indexes': [models.Index(fields=['center_latitude', 'center_longitude'], name='defects_def_center__11b6fe_idx'), models.Index(fields=['cluster_key'], name='defects_def_cluster_7227b8_idx')],
            },
        ),
    ]
