# Generated by Django 5.2.11 on 2026-06-12 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0002_defectcluster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='Отклонён'),
        ),
        migrations.AddField(
            model_name='defect',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_defects', to=settings.AUTH_USER_MODEL),
        ),
    ]
