# Generated by Django 5.2.11 on 2026-06-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='С даты'),
        ),
        migrations.AddField(
            model_name='report',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='По дату'),
        ),
        migrations.AddField(
            model_name='report',
            name='severity',
            field=models.CharField(choices=[('all', 'Все'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('confirmed', 'Confirmed only')], default='all', max_length=20, verbose_name='Уровень критичности'),
        ),
    ]
