# Generated by Django 5.2.11 on 2026-05-08 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_alter_camera_options_camera_description_and_more'),
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streamsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сессия стриминга', 'verbose_name_plural': 'Сессии стриминга'},
        ),
        migrations.AddField(
            model_name='streamsession',
            name='error_message',
            field=models.TextField(blank=True, default='', verbose_name='Ошибка'),
        ),
        migrations.AddField(
            model_name='streamsession',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Остановлен в'),
        ),
        migrations.AlterField(
            model_name='streamsession',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cameras.camera', verbose_name='Камера'),
        ),
        migrations.AlterField(
            model_name='streamsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='streamsession',
            name='fps',
            field=models.FloatField(blank=True, null=True, verbose_name='FPS'),
        ),
        migrations.AlterField(
            model_name='streamsession',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='streamsession',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='streamsession',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Разрешение'),
        ),
        migrations.AlterField(
            model_name='streamsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Запущен в'),
        ),
        migrations.AlterField(
            model_name='streamsession',
            name='status',
            field=models.CharField(choices=[('idle', 'Ожидание'), ('running', 'Запущен'), ('error', 'Ошибка'), ('stopped', 'Остановлен')], db_index=True, default='idle', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='streamsession',
            index=models.Index(fields=['status', 'is_active'], name='streaming_s_status_4ad1f6_idx'),
        ),
        migrations.AddIndex(
            model_name='streamsession',
            index=models.Index(fields=['camera', 'status'], name='streaming_s_camera__5870dc_idx'),
        ),
    ]
